
let home_route="./";
export const img = {

    cart_symb: require(home_route+"Group_u.svg").default,
    cart_purple_symb: require(home_route+"Group_u_purple.svg").default,
    arrow_symb: require(home_route+"Vector_a.svg").default,
    arrow_pink_symb: require(home_route+"vector_a_pink.svg").default,
    phone_symb: require(home_route+"Vector_m.svg").default,
    love_symb: require(home_route+"Vector_q.svg").default,
    love_purple_symb: require(home_route+"Vector_q_purple.svg").default,
    envlp_symb: require(home_route+"Vector_x.svg").default,
    sach_symb: require(home_route+"Vector_k.svg").default,
    sach_purple_symb: require(home_route+"Vector_k_purple.svg").default,
    user_symb: require(home_route+"carbon_user_p.svg").default,
    chair_1: require(home_route+"chair_1.svg").default,
    chair_2: require(home_route+"chair_2.svg").default,
    chair_3: require(home_route+"chair_3.svg").default,
    chair_4: require(home_route+"chair_4.svg").default,
    chair_5: require(home_route+"chair_5.svg").default,
    chair_6: require(home_route+"chair_6.svg").default,
    chair_7: require(home_route+"chair_7.svg").default,
    chair_8: require(home_route+"chair_8.svg").default,
    chair_9: require(home_route+"chair_9.svg").default,
    chair_10: require(home_route+"chair_10.svg").default,
    chair_11: require(home_route+"chair_11.svg").default,
    chair_12: require(home_route+"chair_12.svg").default,
    chair_13: require(home_route+"chair_13.svg").default,
    chair_14: require(home_route+"chair_14.svg").default,
    chair_15: require(home_route+"chair_15.svg").default,
    supp_1: require(home_route+"supp_1.svg").default,
    supp_2: require(home_route+"supp_2.svg").default,
    supp_3: require(home_route+"supp_3.svg").default,
    supp_4: require(home_route+"supp_4.svg").default,
    sofa_1: require(home_route+"sofa_1.svg").default,
    sofa_2: require(home_route+"sofa_2.svg").default,
    sofa_3: require(home_route+"sofa_3.svg").default,
    drawer_1: require(home_route+"drawer_1.svg").default,
    timer_1: require(home_route+"timer_1.svg").default,
    banner_1: require(home_route+"banner_1.svg").default,
    ads_1: require(home_route+"ads_1.svg").default,
    blog_1: require(home_route+"blog_1.svg").default,
    blog_2: require(home_route+"blog_2.svg").default,
    blog_3: require(home_route+"blog_3.svg").default,
    lamp_1: require(home_route+"lamp_1.svg").default,
    "50_off": require(home_route+"50_off.svg").default,

};